services:
  - type: web
    name: manageevent-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ManageEvent-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /api/events

